/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Setup.java
 *
 * Created on May 30, 2011, 3:10:45 PM
 */

package atomicgit;

import javax.swing.JFrame;

/**
 *
 * @author Scott
 */
public class Setup extends javax.swing.JFrame {

    /** Creates new form Setup */
    public Setup() {
        initComponents();
    }

    Setup(JFrame mainFrame)
    {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        userNameTxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        userNameLbl = new javax.swing.JLabel();
        emailTxt = new javax.swing.JTextField();
        emailLbl = new javax.swing.JLabel();
        RepoLbl = new javax.swing.JLabel();
        repoTxt = new javax.swing.JTextField();
        gitSp = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        titleLbl = new javax.swing.JLabel();
        startBtn = new javax.swing.JButton();

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(atomicgit.AtomicGitApp.class).getContext().getResourceMap(Setup.class);
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("Form"); // NOI18N

        userNameTxt.setText(resourceMap.getString("userNameTxt.text")); // NOI18N
        userNameTxt.setName("userNameTxt"); // NOI18N

        jLabel2.setFont(resourceMap.getFont("jLabel2.font")); // NOI18N
        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        userNameLbl.setText(resourceMap.getString("userNameLbl.text")); // NOI18N
        userNameLbl.setName("userNameLbl"); // NOI18N

        emailTxt.setText(resourceMap.getString("emailTxt.text")); // NOI18N
        emailTxt.setName("emailTxt"); // NOI18N

        emailLbl.setText(resourceMap.getString("emailLbl.text")); // NOI18N
        emailLbl.setName("emailLbl"); // NOI18N

        RepoLbl.setText(resourceMap.getString("RepoLbl.text")); // NOI18N
        RepoLbl.setName("RepoLbl"); // NOI18N

        repoTxt.setName("repoTxt"); // NOI18N

        gitSp.setName("gitSp"); // NOI18N

        jLabel6.setFont(resourceMap.getFont("jLabel6.font")); // NOI18N
        jLabel6.setText(resourceMap.getString("jLabel6.text")); // NOI18N
        jLabel6.setName("jLabel6"); // NOI18N

        titleLbl.setFont(resourceMap.getFont("titleLbl.font")); // NOI18N
        titleLbl.setText(resourceMap.getString("titleLbl.text")); // NOI18N
        titleLbl.setName("titleLbl"); // NOI18N

        startBtn.setText(resourceMap.getString("startBtn.text")); // NOI18N
        startBtn.setName("startBtn"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(userNameLbl)
                        .addGap(18, 18, 18)
                        .addComponent(userNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(gitSp))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(12, 12, 12)
                            .addComponent(emailLbl)
                            .addGap(40, 40, 40)
                            .addComponent(emailTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(titleLbl))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(startBtn)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(RepoLbl)
                                .addGap(18, 18, 18)
                                .addComponent(repoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(titleLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(userNameLbl))
                    .addComponent(userNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(emailLbl))
                    .addComponent(emailTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gitSp, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(RepoLbl))
                    .addComponent(repoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(startBtn)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void Setup()
    {
        InstallGit();
        SetupSsh();
        //WriteBatch();
    }

    private void InstallGit()
    {

    }

    private void SetupSsh()
    {

    }


    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Setup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel RepoLbl;
    private javax.swing.JLabel emailLbl;
    private javax.swing.JTextField emailTxt;
    private javax.swing.JSeparator gitSp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField repoTxt;
    private javax.swing.JButton startBtn;
    private javax.swing.JLabel titleLbl;
    private javax.swing.JLabel userNameLbl;
    private javax.swing.JTextField userNameTxt;
    // End of variables declaration//GEN-END:variables

}
